//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibAtem.DeviceProfile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibAtem.DeviceProfile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DeviceProfile&gt;
        ///  &lt;Product&gt;ATEM 1 M/E Production Switcher&lt;/Product&gt;
        ///  &lt;MixEffectBlocks&gt;1&lt;/MixEffectBlocks&gt;
        ///  &lt;Sources&gt;
        ///    &lt;DevicePort id=&quot;1&quot;&gt;
        ///      &lt;Port&gt;Composite&lt;/Port&gt;
        ///      &lt;Port&gt;SVideo&lt;/Port&gt;
        ///      &lt;Port&gt;Component&lt;/Port&gt;
        ///      &lt;Port&gt;HDMI&lt;/Port&gt;
        ///    &lt;/DevicePort&gt;
        ///    &lt;DevicePort id=&quot;2&quot;&gt;
        ///      &lt;Port&gt;HDMI&lt;/Port&gt;
        ///    &lt;/DevicePort&gt;
        ///    &lt;DevicePort id=&quot;3&quot;&gt;
        ///      &lt;Port&gt;HDMI&lt;/Port&gt;
        ///    &lt;/DevicePort&gt;
        ///    &lt;DevicePort id=&quot;4&quot;&gt;
        ///      &lt;Port&gt;HDMI&lt;/Port&gt;
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Atem1MEProductionSwitcher {
            get {
                return ResourceManager.GetString("Atem1MEProductionSwitcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DeviceProfile&gt;
        ///  &lt;Product&gt;ATEM 2 M/E Production Studio 4K&lt;/Product&gt;
        ///  &lt;MixEffectBlocks&gt;2&lt;/MixEffectBlocks&gt;
        ///  &lt;Sources&gt;
        ///    &lt;DevicePort id=&quot;1&quot;&gt;
        ///      &lt;Port&gt;HDMI&lt;/Port&gt;
        ///      &lt;Port&gt;SDI&lt;/Port&gt;
        ///    &lt;/DevicePort&gt;
        ///    &lt;DevicePort id=&quot;2&quot;&gt;
        ///      &lt;Port&gt;SDI&lt;/Port&gt;
        ///    &lt;/DevicePort&gt;
        ///    &lt;DevicePort id=&quot;3&quot;&gt;
        ///      &lt;Port&gt;SDI&lt;/Port&gt;
        ///    &lt;/DevicePort&gt;
        ///    &lt;DevicePort id=&quot;4&quot;&gt;
        ///      &lt;Port&gt;SDI&lt;/Port&gt;
        ///    &lt;/DevicePort&gt;
        ///    &lt;DevicePort id=&quot;5&quot;&gt;
        ///      &lt;Port&gt;SDI&lt;/Port&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Atem2MEProductionStudio4K {
            get {
                return ResourceManager.GetString("Atem2MEProductionStudio4K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DeviceProfile&gt;
        ///  &lt;Product&gt;ATEM Television Studio HD&lt;/Product&gt;
        ///  &lt;MixEffectBlocks&gt;1&lt;/MixEffectBlocks&gt;
        ///  &lt;Sources&gt;
        ///    &lt;DevicePort id=&quot;1&quot;&gt;
        ///      &lt;Port&gt;HDMI&lt;/Port&gt;
        ///    &lt;/DevicePort&gt;
        ///    &lt;DevicePort id=&quot;2&quot;&gt;
        ///      &lt;Port&gt;HDMI&lt;/Port&gt;
        ///    &lt;/DevicePort&gt;
        ///    &lt;DevicePort id=&quot;3&quot;&gt;
        ///      &lt;Port&gt;HDMI&lt;/Port&gt;
        ///    &lt;/DevicePort&gt;
        ///    &lt;DevicePort id=&quot;4&quot;&gt;
        ///      &lt;Port&gt;HDMI&lt;/Port&gt;
        ///    &lt;/DevicePort&gt;
        ///    &lt;DevicePort id=&quot;5&quot;&gt;
        ///      &lt;Port&gt;SDI&lt;/Port&gt;
        ///    &lt;/DevicePort&gt;
        ///    &lt;Devic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AtemTelevisionStudioHD {
            get {
                return ResourceManager.GetString("AtemTelevisionStudioHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DeviceProfile&gt;
        ///  &lt;Product&gt;Unknown ATEM Switcher&lt;/Product&gt;
        ///  &lt;MixEffectBlocks&gt;1&lt;/MixEffectBlocks&gt;
        ///  &lt;Sources&gt;
        ///    &lt;DevicePort id=&quot;1&quot;&gt;
        ///      &lt;Port&gt;SDI&lt;/Port&gt;
        ///    &lt;/DevicePort&gt;
        ///    &lt;DevicePort id=&quot;2&quot;&gt;
        ///      &lt;Port&gt;SDI&lt;/Port&gt;
        ///    &lt;/DevicePort&gt;
        ///    &lt;DevicePort id=&quot;3&quot;&gt;
        ///      &lt;Port&gt;SDI&lt;/Port&gt;
        ///    &lt;/DevicePort&gt;
        ///    &lt;DevicePort id=&quot;4&quot;&gt;
        ///      &lt;Port&gt;SDI&lt;/Port&gt;
        ///    &lt;/DevicePort&gt;
        ///    &lt;DevicePort id=&quot;5&quot;&gt;
        ///      &lt;Port&gt;SDI&lt;/Port&gt;
        ///    &lt;/DevicePort&gt;
        ///    &lt;DevicePort id [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
